import tkinter as tk
from tkinter import ttk 

##put circles,

root = tk.Tk()
root.title("Connect 4")
game = ttk.Frame(root)

X0Ylevel = ""
X1Ylevel = ""
def yeah():
    print("yeah")

def drawBoard():
    X0Y0 = tk.Canvas(game, bg="gray", height=50, width=50)
    X0Y0.grid(row=0, column=0)
    X1Y0 = tk.Canvas(game, bg="gray", height=50, width=50)
    X1Y0.grid(row=0, column=1)
    X2Y0 = tk.Canvas(game, bg="gray", height=50, width=50)
    X2Y0.grid(row=0, column=2)
    X3Y0 = tk.Canvas(game, bg="gray", height=50, width=50)
    X3Y0.grid(row=0, column=3)
    X4Y0 = tk.Canvas(game, bg="gray", height=50, width=50)
    X4Y0.grid(row=0, column=4)
    X5Y0 = tk.Canvas(game, bg="gray", height=50, width=50)
    X5Y0.grid(row=0, column=5)
    X6Y0 = tk.Canvas(game, bg="gray", height=50, width=50)
    X6Y0.grid(row=0, column=6)

    X0Y1 = tk.Canvas(game, bg="gray", height=50, width=50)
    X0Y1.grid(row=1, column=0)
    X1Y1 = tk.Canvas(game, bg="gray", height=50, width=50)
    X1Y1.grid(row=1, column=1)
    X2Y1 = tk.Canvas(game, bg="gray", height=50, width=50)
    X2Y1.grid(row=1, column=2)
    X3Y1 = tk.Canvas(game, bg="gray", height=50, width=50)
    X3Y1.grid(row=1, column=3)
    X4Y1 = tk.Canvas(game, bg="gray", height=50, width=50)
    X4Y1.grid(row=1, column=4)
    X5Y1 = tk.Canvas(game, bg="gray", height=50, width=50)
    X5Y1.grid(row=1, column=5)
    X6Y1 = tk.Canvas(game, bg="gray", height=50, width=50)
    X6Y1.grid(row=1, column=6)

    X0Y2 = tk.Canvas(game, bg="gray", height=50, width=50)
    X0Y2.grid(row=2, column=0)
    X1Y2 = tk.Canvas(game, bg="gray", height=50, width=50)
    X1Y2.grid(row=2, column=1)
    X2Y2 = tk.Canvas(game, bg="gray", height=50, width=50)
    X2Y2.grid(row=2, column=2)
    X3Y2 = tk.Canvas(game, bg="gray", height=50, width=50)
    X3Y2.grid(row=2, column=3)
    X4Y2 = tk.Canvas(game, bg="gray", height=50, width=50)
    X4Y2.grid(row=2, column=4)
    X5Y2 = tk.Canvas(game, bg="gray", height=50, width=50)
    X5Y2.grid(row=2, column=5)
    X6Y2 = tk.Canvas(game, bg="gray", height=50, width=50)
    X6Y2.grid(row=2, column=6)

    X0Y3 = tk.Canvas(game, bg="gray", height=50, width=50)
    X0Y3.grid(row=3, column=0)
    X1Y3 = tk.Canvas(game, bg="gray", height=50, width=50)
    X1Y3.grid(row=3, column=1)
    X2Y3 = tk.Canvas(game, bg="gray", height=50, width=50)
    X2Y3.grid(row=3, column=2)
    X3Y3 = tk.Canvas(game, bg="gray", height=50, width=50)
    X3Y3.grid(row=3, column=3)
    X4Y3 = tk.Canvas(game, bg="gray", height=50, width=50)
    X4Y3.grid(row=3, column=4)
    X5Y3 = tk.Canvas(game, bg="gray", height=50, width=50)
    X5Y3.grid(row=3, column=5)
    X6Y3 = tk.Canvas(game, bg="gray", height=50, width=50)
    X6Y3.grid(row=3, column=6)

    X0Y4 = tk.Canvas(game, bg="gray", height=50, width=50)
    X0Y4.grid(row=4, column=0)
    X1Y4 = tk.Canvas(game, bg="gray", height=50, width=50)
    X1Y4.grid(row=4, column=1)
    X2Y4 = tk.Canvas(game, bg="gray", height=50, width=50)
    X2Y4.grid(row=4, column=2)
    X3Y4 = tk.Canvas(game, bg="gray", height=50, width=50)
    X3Y4.grid(row=4, column=3)
    X4Y4 = tk.Canvas(game, bg="gray", height=50, width=50)
    X4Y4.grid(row=4, column=4)
    X5Y4 = tk.Canvas(game, bg="gray", height=50, width=50)
    X5Y4.grid(row=4, column=5)
    X6Y4 = tk.Canvas(game, bg="gray", height=50, width=50)
    X6Y4.grid(row=4, column=6)

    X0Y5 = tk.Canvas(game, bg="gray", height=50, width=50)
    X0Y5.grid(row=5, column=0)
    X1Y5 = tk.Canvas(game, bg="gray", height=50, width=50)
    X1Y5.grid(row=5, column=1)
    X2Y5 = tk.Canvas(game, bg="gray", height=50, width=50)
    X2Y5.grid(row=5, column=2)
    X3Y5 = tk.Canvas(game, bg="gray", height=50, width=50)
    X3Y5.grid(row=5, column=3)
    X4Y5 = tk.Canvas(game, bg="gray", height=50, width=50)
    X4Y5.grid(row=5, column=4)
    X5Y5 = tk.Canvas(game, bg="gray", height=50, width=50)
    X5Y5.grid(row=5, column=5)
    X6Y5 = tk.Canvas(game, bg="gray", height=50, width=50)
    X6Y5.grid(row=5, column=6)

##copy this for each column
    button = ttk.Button(game, text="drop", command=yeah) 
    button.grid(row=6,column=0,sticky="W") 
    button1 = ttk.Button(game, text="drop", command=yeah) 
    button1.grid(row=6,column=1,sticky="W")
    button2 = ttk.Button(game, text="drop", command=yeah) 
    button2.grid(row=6,column=2,sticky="W")
    button3 = ttk.Button(game, text="drop", command=yeah) 
    button3.grid(row=6,column=3,sticky="W")
    button4 = ttk.Button(game, text="drop", command=yeah) 
    button4.grid(row=6,column=4,sticky="W")
    button5 = ttk.Button(game, text="drop", command=yeah) 
    button5.grid(row=6,column=5,sticky="W")
    button6 = ttk.Button(game, text="drop", command=yeah) 
    button6.grid(row=6,column=6,sticky="W")

    game.pack()
drawBoard()

root.mainloop()